/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'greenMangoSoda' : IDL.Null,
  'lemonSoda' : IDL.Null,
  'general' : IDL.Null,
  'jeeraSoda' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : Category,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
  'updateProductAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateProductDescription' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProductPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'greenMangoSoda' : IDL.Null,
    'lemonSoda' : IDL.Null,
    'general' : IDL.Null,
    'jeeraSoda' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : Category,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Category],
        [],
        [],
      ),
    'updateProductAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateProductDescription' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProductPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };