/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'greenMangoSoda' : null } |
  { 'lemonSoda' : null } |
  { 'general' : null } |
  { 'jeeraSoda' : null };
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'productInterest' : Category,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'price' : bigint,
}
export interface _SERVICE {
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'seedProducts' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string, Category], undefined>,
  'updateProductAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'updateProductDescription' : ActorMethod<[bigint, string], undefined>,
  'updateProductPrice' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];